textIntentDetect_test (unfinish) mocha
deepdialog/xiaojuzi pull request #2
Opened 2022-01-20 09:48 UTC by tianrking

2022-01-22 06:45 UTC, qhduan requested changes

2022-01-22 06:45 UTC, qhduan commented on package.json
> +    "mocha": "^9.1.4",
nodejs有一个专门的devDependencies……你可以搜一下，mocha应该放到那里面

2022-01-22 06:45 UTC, qhduan commented on test/a_welcome.js
> +    // let r = await hello();
有些代码清理一下，在合并到主分支之前

2022-01-22 06:45 UTC, qhduan commented on test/a_welcome.js
> +const promisic = function (func) {
这些没必要留着吧，理解就好了吧，用到了吗

2022-01-22 06:45 UTC, qhduan commented on test/a_welcome.js
> +  };
这个标志的意思是，你的文件末尾应该有个空行（一个比较老的lint规矩）

2022-01-22 06:45 UTC, qhduan commented on test/keyword_jz_test.js
> +        const _res_3 = await textIntentDetect(args_3,payload_3);
文件整体很多地方没有lint，参考一下执行 eslint test/命令看看，yarn lint执行的是package.json里面的eslint src/

2022-01-22 06:45 UTC, qhduan commented on test/myfile_test.js
> +            return '我的文件 txt.jpg'
我的文件这个命令应该是没参数的

2022-01-22 06:45 UTC, qhduan commented on test/myfile_test.js
> +        intent: 'todo'
intent结果也不应该是todo吧

2022-01-23 12:57 UTC, tianrking commented on test/myfile_test.js
> +        intent: 'todo'
{ roomTopic: null, isRoom: false, text: '我的文件', intent: 'list-file' }

list-file

2022-01-23 12:59 UTC, merged